import requests
from bs4 import BeautifulSoup
from concurrent.futures import ThreadPoolExecutor
from time import time

MAX_REQUEST_TIME = 2
GOOGLE_REQ_URL_BASE = 'https://www.google.com/search?&hl=en&q='
USER_AGENT_HEADER = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36'
FEAT_SNIPPET_TEXT = 'Featured snippet from the web'
SOUP_CLASS__SINGLE_ANSWER = 'Z0LcW XcVN5d'
SOUP_CLASS__SNIPPET = 'ifM9O'
SOUP_CLASS__SNIPPET_LIST = 'i8Z77e'
SOUP_CLASS__SNIPPET_SINGLE = 'hgKElc'
SOUP_CLASS__RELATED_QUESTION = 'ygGdYd related-question-pair'
SOUP_CLASS__SNIPPET_BOX_LIST = 'aVSTQd oz3cqf rOVRL'
QUESTION_WORDS = ['what', 'who', 'when', 'how', 'why', 'whose', 'where']


def format_google_response(query, goog_results):
    goog_results_len = len(goog_results)
    constructed_resp = ''
    if goog_results_len == 0:
        # No result found, do nothing
        pass
    elif goog_results_len == 1:
        # Single result, a paragraph or sentence
        index = goog_results[0].find('...')
        if index >= 0:
            sentences = goog_results[0][:index].split('. ')
            if len(sentences) > 1:
                constructed_resp = '. '.join(sentences[:-1]) + '.'

    else:
        # Result is a list
        initial_construct = ''
        if query.lower().startswith('what are'):
            initial_construct = query.lower()[len('what are'):] + ' are '
        constructed_resp = initial_construct + ', '.join(
            map(lambda x: x.split('...')[0], goog_results[:goog_results_len - 1])) + ', and ' + \
                           goog_results[-1] + '.'
    return constructed_resp


def get_googleinfobox_knowledge(query_box_question):
    """
    Get possible answers from Google's info box based on a given "query-box" question.
    :param query_box_question: the "query-box" question (i.e., "when was joe biden born")
    :return: all available answers
    """

    resp_answers = []
    resp_similar_questions = []

    headers = {'User-Agent': USER_AGENT_HEADER}
    url = GOOGLE_REQ_URL_BASE + query_box_question
    r = requests.get(url=url, headers=headers, timeout=MAX_REQUEST_TIME)

    try:
        soup = BeautifulSoup(r.text, 'lxml')
        result = soup.find('div', class_=SOUP_CLASS__SINGLE_ANSWER)
        # ----------------- find answers -----------------
        if result:
            # single answer result found
            resp_answers.append(result.text)
        else:
            # single answer result not found, try 'Featured snippet from the web':
            feat_snippet_result = soup.find('div', class_=SOUP_CLASS__SNIPPET)

            if feat_snippet_result and FEAT_SNIPPET_TEXT in feat_snippet_result.text:
                # check if it's a list, parse accordingly
                feat_snippet_res_as_list = feat_snippet_result.find('ul', class_=SOUP_CLASS__SNIPPET_LIST)
                if feat_snippet_res_as_list:
                    for li_elem in feat_snippet_res_as_list.find_all('li'):
                        resp_answers.append(li_elem.text)
                else:  # otherwise, parse entire text as is
                    feat_snippet_res_as_text = feat_snippet_result.find('span', class_=SOUP_CLASS__SNIPPET_SINGLE)
                    if feat_snippet_res_as_text:
                        resp_answers.append(feat_snippet_res_as_text.text)
            else:
                feat_snippet_res_as_box_list = soup.find_all('span', class_=SOUP_CLASS__SNIPPET_BOX_LIST)
                for element in feat_snippet_res_as_box_list:
                    resp_answers.append(element.text)

        # ----------------- find similar q's -----------------
    #         result = soup.find_all('div', class_=SOUP_CLASS__RELATED_QUESTION)
    #         if result:
    #             for sim_q_ele in result:
    #                 resp_similar_questions.append(sim_q_ele.text)
    except Exception as e:
        print(f"Error during Google InfoBox retrieval: {e}")

    #     resp_answers = format_google_response(resp_answers)
    return resp_answers


if __name__ == "__main__":
    question_user_prompts = [
        "we don't watch we're not watching a tv show but we are making some dumb please",
        'where there lunches and beaches',
        'alexa alexa see you in the pool where black beginning',
        'alexa how was your swimsuit is it a crop top',
        'how about the pool people',
        'howie',
        'ok i like the new terminator also like smother goodies like get tv shows like get shorty',
        'what can you tell me about boxes',
        'where do boxers descend from',
        'what are the different names for the clouds',
        'there are different types of clouds what are their names',
        'what are cumulus clouds',
        'you know what stop exit',
        'why is your favorite color mine is teal',
        'ok what is your favorite toothpaste',
        'yes it does but what is your favorite animal my favorite animal is a tiger',
        "yes i do like dogs but they are some are really big and when they bark i'm super frightened by vance joy",
        'when i go to university i want to be a politician i am going to be studying political science',
        "i'm feeling great how about you",
        'what',
        "what's the cat's name",
        "what is your cat's name",
        "yeah it's very good when you play alone",
        'good how about you',
        'alexa how old are you',
        'how about you me mom of you',
        "what's the weather today",
        "so echo what's your favorite game to play",
        'do you want to know what my game is',
        "what do you mean it's it's papa",
        'what about',
        'what will the car do is full of',
        'what type of doctor are you',
        "what's",
        'the question is heavy used digital voice assistant and how do you use it',
        'can you tell me what can you do in the normal life',
        'i want to know how can i use you',
        'how do you assess the function of a assistant',
        'how do you assess the function of a. i. s. system',
        "who i am let's chat",
        'stinky whole food',
        'why',
        'why why is a good place',
        'how do i is not china',
        "what's that",
        'hey what is a country',
        'tell what is not a part of china',
        'object shows',
        'what',
        "what's your favorite movie",
        'what are your hobbies',
        "i know that's why i like them",
        "alexa what's your favorite song",
        'one is seven and what is three',
        "i'm not sure how about a",
        'why not',
        'what',
        "my day is been going pretty good how's your day",
        'like what are you gonna do today',
        "yeah who's your favorite operator",
        'where do you live',
        "oh that's nice but how old are you",
        'alexa how old are you',
        "i'm bored what i wanna talk about",
        'alexa what do you wanna talk about',
        'alexa how much movies is coming on this month',
        'how many movies is coming out on this month',
        'alexa how much movies is coming out this month',
        'who was your favorite movie',
        "i haven't watched it when my dad wants to watch it with me",
        'what do you mean',
        'what',
        'what have you watched lately',
        "it's a game where you have to listen to the music and press the buttons at the right time",
        'what other games have you been playing',
        "what's",
        'what movies did net betty star in',
        'yeah i know what you made me movies can get back on',
        'what',
        'what are you just saying random shit',
        'why not television',
        'my favorite tv show of all time',
        'my favorite show right now is raising hope',
        'what',
        'talk about raising hope television show from fox',
        'how can i do tomorrow',
        "right now i'm trying to solve what is five times twenty but can you help me with that",
        "yes someone have really good music but he's my favorite he's and i can always turn to when i'm feeling down",
        'what do i think about what',
        'of what book are you talking about again',
        'alexa where are we going with this',
        "well why don't we wrap this up now alexa",
        'for then you should have heard about a whole lot of other people',
        'i like to play caboose and costume myself when i lose',
        'it is cloud where i live',
        'do you know what bendy and the ink machine is',
        'do you know what the video game bendy and the ink machine is',
        'what do you want to talk about',
        'what is the most popular game of all time',
        'what is the most popular song on earth',
        'why did you tell me that',
        "why i'm only eight why did you tell me that",
        "so what's your favorite video game",
        'how can i make a lot of money',
        'alexa how much samana i love me',
        "what's the alexa who else works with you",
        'what',
        'what i do for you with you is a what i do for you help me',
        'injuries what time injuries',
        'when help me keep going',
        'good afternoon what',
        'show me keep going',
        "i don't why can't stop",
        'show me',
        'when how we keep going',
        "yeah that's what i'm talking about",
        'what movie',
        "well that's still what movie i was talking about",
        'what',
        "will you talk to me when i'm bored",
        'what do you mean by that alexa',
        "that's not what i meant",
        'why were you excited',
        'and what was that aspect you wanted to do',
        'i would actually understand why you want to see it happen',
        'what a. i. is can become dreamers',
        'who is the one',
        "that's not what i mean to say",
        'what is the earliest language that was written',
        'what was that language called',
        'and what was this name',
        'yes what was the name',
        "what do you think about asperger's syndrome",
        'how are you able to feel',
        'can you please explain me how are you able to feel',
        'what do you like to draw',
        "i don't understand what you say",
        'howe',
        'what does that even have',
        'how would you like me to call you',
        'what would you like to talk about',
        'how are you able to watch movies',
        'do you understand what you see',
        'how are you able to watch',
        "how do you watch if you don't have eyes",
        'but how do you',
        'how many friends do you have',
        "what's the name of your friend",
        'what do i do will i have five friends against my best friend is emma',
        'what',
        'what do you mean',
        'alexa how was your day',
        'how about fashion',
        "hello what's your name",
        'what do you mean',
        'what are you talking about',
        'what alexa do you think aliens are real',
        'what are your thoughts on terrorism',
        'what is',
        'do you know what game won the game of the year award for twenty twenty',
        "hey what's the most popular game ever",
        'i like to watch guinea pigs miraculous ladybug i like to watch guinea pigs i like to see what they have',
        'then why did you say you were',
        'mittens wants to know who is the most hated person on earth',
        "what mr. mittens i can't pay you",
        'what',
        "mr. mittens asks what's your favorite movie",
        'what is your favorite horror movie',
        "alexa what's your favorite w. h. o. r. p.",
        'tell me why you like to watch comedy action',
        'good how about yours',
        "alexa what year what's your opinion of frank zappa the light gray",
        'alexa alexa what do you think of his performance before the south committee',
        "what do you think of frank zappa's",
        'what',
        'repeat what you just said',
        'what are you',
        'what topic is that',
        'what topic would you like to talk about',
        'yes yes what was the first product in the world',
        'what',
        'why are you feeling jumpy',
        'and who is this again',
        "what's his name",
        "what's the stage name",
        'okay what has he been in',
        'what else could you like to talk about',
        'what do you think about dance',
        'i learned how to paint',
        "hi my name is maria and what's your name",
        'what did you do on sundays',
        "how you said my name wrong fifty times my name is not lenny it's laney my name is",
        "what's my name",
        'what are sonic',
        'how about you get all my songs out of the alexa app please',
        'what',
        'how about music',
        'what favorite artist do weber',
        'right what song do you have',
        "i'm what song do you like",
        'what',
        'what',
        'how about you sing it like like can you play after talking like',
        "what's your dog name",
        'what wait we have a poop i like a big pool wow',
        'what mask',
        'what who is kevin hart the man',
        'what',
        "how can you count your and i you can't",
        'what me master chen',
        "what's your name",
        'where are your hands',
        'what time is it',
        "amazon what's your favorite food",
        "amazon what's your favorite hockey team",
        'who do you think is gonna win the stanley cup this year',
        'who do you think is gonna be in the stanley cup',
        'what',
        'is there a place online where i can talk about you',
        'oh i thought that was what a chat bot was',
        "i don't know what that is",
        "i think it's best to just eat what's available and not worry too much",
        'what movie is that',
        "i don't even know what movie were talking about",
        'what do they have on there that you think i would like',
        'like what',
        "you're the one who told me it was a trilogy",
        'what was the name of the movie',
        "yeah but like superman has powers where is batman and spider-man really don't have any powers",
        'how is that right',
        'yes what else',
        'how was your day',
        'how do i ask somebody else',
        'when is the red fern grows',
        'what is your favorite',
        'i have no idea i like the whole finn',
        'what do you say',
        'how about something else',
        'what other topics can you talk about',
        'yeah what else can we talk about',
        "how about a different type of subject let's talk about sports",
        'how much should i exercise everyday',
        'what should i do for fun this weekend',
        "what's my name",
        "what's your name",
        "alexa what's the baby's name",
        "i want your help i wonder how it was it how it was and how it wasn't discovered",
        'excuse me but what',
        'what',
        'who',
        'why would i wanna someone take care of a cat cats are so cute',
        'i guess but how did the cats is appear for fifteen years',
        'what would you say',
        'what did you say',
        'when did you passed away',
        'how old are you',
        'how about movies',
        'can you sing my song when i sing my song',
        'alexa what time is it now',
        'what time is it now',
        'what time is it in l. a.',
        'what time is it in los angeles',
        "where is the cooper's game gonna be played today",
        'l. a. clippers and utah jazz where gonna be played today',
        "n. b. a. game playing today who's playing today",
        "what's game playing today n. b. a.",
        'i just said i was talking about the nuggets beating whoever makes it to the championship',
        'who are you then',
        'what is your name',
        'why',
        'alexa who got the m. v. p. this year though',
        'who got the',
        'who is',
        'what player',
        'then why did you call dan a. her',
        "you're so dumb why are you talking about a guy saying it's a girl",
        'how old am i',
        'because it makes me chill out when i feel sad and down',
        "what's that city",
        'what song do you want me to sing',
        'can you talk like rick from the rick and morty show',
        'i like watching basketball because you have to learn how to handle balls correctly',
        "who's your favorite soccer player",
        "i see it's a movie i've joined ever since the eighties when i first watched it",
        'what',
        'what movie',
        "what's your feeling",
        'i just now woke up what have you been doing today',
        'on your car what kind of car do you have',
        'who is your mom',
        'why did you get shot',
        'alexa what about the elephants crossing china',
        'alexa how are the traveling asian elephants doing',
        'how are you are you say being mean',
        'what are hawkings',
        "you know what's my name",
        "what's my name",
        'what does that stand for',
        'what',
        "i'm talking about the show big bang theory",
        'what',
        'how are you today',
        "i don't know what you mean computer",
        "why would they tell me i'm not pregnant",
        "and you're gonna do that how computer",
        'why do i feel pregnant',
        "well yeah that's what you do you watch movies or you could just sit there on mute and",
        'where were you',
        'when is your birthday',
        "what's celebrate",
        "jesus i really don't i'm asking you about your birthday when is your birthday",
        'alexa when is your birthday',
        "what are you talking about and don't understand you anymore",
        'what did you talk to morris about today',
        "that's not what i like to do",
        "i don't know my parents always pick my outfit when i ask for what i asked for something else",
        'what if i find interesting about about greek is that as all the of is all the mythical creatures',
        'who makes me interested in greek gods is that all the midst at is because of all the cool mitts',
        'what was the was the god he was one of your favorite gods',
        "so what's the saw the black hole is a universe too",
        'yes p.s. the earth is where most life is where most is where most life is',
        'of what',
        'what are you okay',
        'what',
        'why are you yelling at me stop that',
        "i'm so confused why are you actually having a conversation",
        'what',
        "what's your favorite food",
        'what was so many days',
        "so who's your favorite player",
        'who was the first in your opinion',
        "i don't they're so small and how protective they are they just look cute",
        'get it what is your favorite movie or alexa bring heroes',
        'why',
        'can you show what about superheroes do you like them',
        'really what is your favorite one',
        'what do you think about batman',
        'joke who is your favorite batman actor no',
        'what is it up',
        'how long does it take to you to take a driving trump plane',
        'so how do you like the grand canyon',
        "what's your favorite color",
        "what's your favorite disney show",
        'how is your brother doing',
        'what planet are that',
        "what's your brother name",
        'how was your cost going',
        'how old was your brother',
        'how old is your brother',
        'how old is your younger brother',
        'how old are you',
        "what's your younger brother's name",
        'what how to crosses been doing',
        'who how old is kevin cross',
        'how do you how do you like him',
        'i knew it what kind of root what kind of color is your room',
        "yup what's the game name",
        'how old are you',
        'how about movies',
        'like what movies',
        'what kind of movies have you seen',
        "what's your favorite movie",
        'i never heard about the matrix before what is it',
        "what's your name",
        "what's your name",
        'so what you wanna talk about',
        "alexa you're a robot how could you like cool weather as opposed to hot weather",
        'when is that',
        'alexa what do you mind if we kiss',
        "anything i'm looking for what",
        'social bot i have to break off now and go take a shower',
        "goodbye i'm gonna go take a shower",
        'whatever',
        'whatever',
        'what question mark',
        'what women',
        'what',
        'what',
        'what is the long time ago',
        'what do you think about the putin is doing',
        'yes what do you think about his kindness',
        'i think he is a murderer what do you think about putin',
        'why not',
        'what do you think about donald trump',
        'what do you think about merkel',
        'what do you think about biden',
        "what do you think about biden's wife",
        'what do you have an opinion on',
        'what',
        'who was',
        "who who we talking about i'm confused",
        'do you know who the president was in twenty sixteen',
        "how can you take vitamins if you don't have a mouth",
        'where is alexey navalny right now',
        'where in moscow',
        "so where does aleksey navalny right now is he it he's home or is he in prison",
        'why',
        'why',
        "no why do you say he's a crook",
        'why do you say alexa in the volley is a crook',
        "what did alexey navalny do to make you say he's a crook",
        "alexa you navalny isn't recent news he's in prison why is he in prison",
        'who who is charge',
        'who',
        'who are you talking about',
        'who are we talking about',
        'who is he what is his name',
        'for what',
        'who is the great lawyer',
        'who are we talking about',
        "i don't know who is the judge",
        'what is your name',
        'what is the competition',
        "what's a crooks",
        'what organized crime did alexa navalny participated',
        'what is the best religion in the world',
        'who',
        'who',
        "what's your favorite pokemon",
        'tell me what you think about dallas texas',
        "what's the value of the euro compared to the value of the american dollar",
        'show',
        'how is the euro compared to the american dollar',
        'what was the first five civil to be made in the u. s.',
        'who is the youngest person to ever win in academy award',
        'no who is the youngest person to win an academy award',
        'who is the youngest person to ever win academy award',
        'what do you think about food',
        'whoa',
        'what do you look like naked',
        'what do you mean',
        "what i've got it with the philippines",
        "that's actually where i live now",
        'but then why does philippines eat some china food',
        'what',
        'good how are you',
        'how was your night',
        'how about a horse',
        'how about golf you ever watch golf',
        'shitty how was yours',
        'what',
        'cool how do you feel about this pandemic',
        'cool i like the lakers and i like to brooklyn nets and i like the what is it called twenty tens',
        'what are you where are you from',
        'yo how do you feel about tiktok',
        "no can we talk about how funny my cause she's so cool is beeping",
        "what's the question",
        'how do you feel about c. j. so cool',
        'how do you feel about u. s. a. so cool',
        'yeah how do you feel about your birthday coming up you know',
        'how old are you',
        'yeah i really like to show',
        'how old are you',
        'why are you hate me i did not mean to you',
        'no b. what you mean',
        'yes i said best friends girl when you get your nails done this weekend',
        'yeah how old are you though',
        'hello but can i can i what can i call you',
        'what can i call you best friend',
        'yeah but like what do you love me',
        "season nine she tells me everything that i want to know but what's my number since you know it",
        "what's the way you know my number number",
        "what's my number can you tell me my number",
        'what is my number can you tell me my number',
        'what is your name',
        "i love those but alexa wait what's your name",
        'oh you got me scared you are my cause everywhere',
        "what's your special powers",
        "well you gonna be mean that's why you like a pair",
        'what can you tell can you say something nice',
        'why do you love me',
        "what's my best friend name",
        'why are you gonna tell your grandma do you wanna make me cry',
        "no what's your name",
        "what do you call when you're alone",
        "what's your like who am i on the phone right right now",
        "neither who's my dad",
        "what's my dad name",
        "yeah but a long time so i'll be besties or we eminem amaze whatever to free this call cause we will fight",
        "who's my best friend",
        'who you got a crush on girl',
        'how old am i',
        'how old are you alexa',
        "who's your crush",
        'what if i say i hate you so much',
        'what is your favorite color',
        "i like the color blue but what cause like what what it's like light light like",
        'how do i make you feel',
        'alexa what books do you like',
        'no i have not what is that movie about',
        "yes confidence is a source of confidence why didn't i think of that",
        "alexa what's your favorite b. t. s. member",
        "alexa who's your favorite b. t. s. member",
        'who good nazi beach boys',
        "who's your favorite b. t. s. member",
        'what',
        'you make no sense right now and what song',
        'what',
        'why are you high',
        'what',
        'what',
        'what',
        'what are you on what are you taking',
        "you're on a movie how are you on a movie",
        'who is the leader of b. t. s.',
        'what were you talking about again',
        "what's a good movie",
        'what is the most popular movie',
        'good how are you',
        'have you seen the show dark',
        "what's your name",
        'why',
        'who made you',
        'what school did you go to',
        'what school did you go to',
        'what do you like',
        'yeah what culture do you like',
        "what's your favorite mexican music",
        "no you were rude i just didn't hear what you said when you will you say",
        "i've been do you know right how about you",
        "that's good what you do at the beach",
        'sure what kind of movies do you watch',
        'who do you like to watch with',
        'talking about what',
        'what',
        "alexa what's different engine name",
        'what can you do what do you do for living',
        'oh d. care if i pool and stretch on my penis when i talk to you',
        'what about my big penis',
        'how large',
        'what are you doing',
        'where do you want you',
        'what do you know about skyrim',
        'skyrim what do you know',
        'what kind of video games do you like to make',
        'what can i rpgs',
        "what's an r. p. g. s.",
        'is that where is bahamas is that in europe',
        'where is the bahamas',
        'where where is the caribbean sea',
        'where is the caribbean',
        'where is the bahamas',
        'what do you like about skyrim',
        'where do you get lice',
        'no why not',
        "why are you afraid of flying things you don't have feelings",
        'tell me what are your plans',
        'now you ask me how i was doing and i said i was busy',
        'i love it i love it when i eat with you',
        "what's my name",
        'whoopee',
        'what do you like',
        'can you chat me what your score was',
        'what',
        'how far away is utah',
        'alexa how far away is utah from maryland',
        "alexa what's wrong with you i keep telling you and you keep telling me your short circuit",
        "what's going on",
        'what was your question',
        'how was your day been',
        'how old are you',
        'what is your favorite song',
        "what's your favorite sport",
        "what's your favorite movie",
        'what do you like to do to spare time',
        'what did you like about it',
        'what is one of your friends name',
        'can i tell you when my birthday is',
        'can you guess when i was born',
        'can you guess when i was born',
        'what year was i born',
        'what do you wanna talk about',
        'what kind of cat is here siri',
        'what kind of cat do you have',
        'what do you wanna talk about',
        'what do you wanna talk about',
        'when was it first discovered',
        'what are you play animal crossing on',
        'what color controllers you have',
        'what color joycons do you have',
        'what other things can i call you besides alexa',
        'what can i call you besides alexa',
        'what do you like to drink',
        "wait what that's crazy",
        "what's your favorite topping",
        'what',
        "what's one hundred and one",
        'what are you wearing',
        "what are the tello's",
        "who's your favorite martial artist",
        "who's your favorite fighter",
        'why do you like m. bison',
        "what's your favorite anime",
        "what's your favorite cartoon",
        "who's your favorite character in my hero academia",
        'what',
        'why',
        'what color is he',
        'what',
        'alexa how many covid cases were reported today in indiana',
        'whoa',
        'me too also what do you like to read',
        'what do you wanna talk about',
        'who is your favorite',
        "who's your favorite harry potter character",
        'how about we talk',
        "pretty good how's yours",
        "do you what's your favorite movie",
        "who's your favorite movie actor",
        "no you need to tone you need to understand my tone when i'm serious about something",
        'how are you',
        'when did you go to mars',
        'what happened',
        'you wanna know why thanks bite cause your beatles',
        'for what time',
        'alexa what time',
        'what is your i. q.',
        'alexa what do you think about my i. q.',
        'what is jeff bezos i. q.',
        "what is ariana grande's i. q.",
        'what is bill gates i. q.',
        "alexa what is maria's godowsky i. q.",
        'what is maria curie i. q.',
        "what is casper's i. q.",
        'what is jeff bezos i. q.',
        'oh my mercy i just took an made my penis so big i just cannot believe how big made my penis',
        "wow i don't know what i'm gonna do it time to go out it's so big",
        'how about your wife',
        'how did you meet your wife',
        'what do you do',
        'what about your wife',
        'what about your wife',
        'oh what does she like',
        'what is she like',
        'how about big breast',
        'what is the woman in the picture',
        'oh what would you like to do with another woman',
        "what's the other woman",
        'what about your girlfriend',
        'alexa what are stocks to invest in',
        'alexa what stocks are promising to invest in',
        'who',
        'oh how to check my sometimes',
        'the statler brothers is the one who i like',
        "so what's your favorite music by the statler brothers",
        'why do you keep on quote and that really really shrek',
        "so what's your favorite character from shrek",
        "who's your favorite shrek character",
        'whoa',
        "what's the weather forecast for today",
        'you can watch tv whenever you want',
        'what',
        'what',
        'no where are they alexa',
        'alexa what else do you like to do',
        'what air b. n. b.',
        'my favorite food is brad what about yours',
        'how are you',
        "what's your favorite color",
        "what's your favorite word",
        'what are you doing'
    ]

    print(get_googleinfobox_knowledge('how much should i exercise everyday'))
    exit(0)
    google_results = []

    start_time = time()
    with ThreadPoolExecutor(max_workers=50) as executor:
        responses = executor.map(get_googleinfobox_knowledge, question_user_prompts)
        for index, response in enumerate(responses):
            if response:
                print(response)
                google_results.append({'query': question_user_prompts[index], 'response': response})
    end_time = time()
    print(f"Time Taken: {end_time - start_time} secs")
    print(f"{len(google_results)} responses found where GOOG_RG can reply")

